### ISSUE TITLE
AttributeError: 'CRD' object has no attribute 'lower'

### ISSUE THREAD

**Issue by mtrower** [ZachWerginz/PolarFlux#10]
```
Calculating polar parameters
Traceback (most recent call last):
  File "python/zaw_pf_script.py", line 249, in <module>
    main()
  File "python/zaw_pf_script.py", line 244, in main
    process(segment, date_c) 
  File "python/zaw_pf_script.py", line 189, in process
    calc_pol(data, mgnt, 'north', seg.meta)
  File "python/zaw_pf_script.py", line 90, in calc_pol
    pole = pole.lower()
AttributeError: 'CRD' object has no attribute 'lower'
```

introduced f5e2e0320ded305c84c3a6db6693f27190563a8e

**Comment by mtrower** [comment]
invalid
